@OrderManagementSystem_HostAddress = http://localhost:5120
@OrderManagementSystem_HostAddress = https://localhost:7279


### Register New User
POST {{OrderManagementSystem_HostAddress}}/api/Auth/register
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Admin@123",
  "role":"Admin"
}

### Login and Get JWT Token
POST {{OrderManagementSystem_HostAddress}}/api/Auth/login
Content-Type: application/json






















### Get All Orders
GET {{OrderManagementSystem_HostAddress}}/api/Orders
Accept: application/json
Authorization: Bearer gjiDIGNymraFK5oqcU96ZMFABYOv8DeAJC1XVkXPN8U=

###

### Create a New Order
POST {{OrderManagementSystem_HostAddress}}/api/Orders
Content-Type: application/json
Accept: application/json
Authorization: Bearer gjiDIGNymraFK5oqcU96ZMFABYOv8DeAJC1XVkXPN8U=

{
  "customerName": "John Doe",
  "product": "Laptop",
  "amount": 1200.50,
  "status": "Pending"
}

###

### Update an Existing Order
PUT {{OrderManagementSystem_HostAddress}}/api/Orders/1  {{-- Replace 1 with an actual Order ID --}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer gjiDIGNymraFK5oqcU96ZMFABYOv8DeAJC1XVkXPN8U=

{
  "customerName": "Jane Smith",
  "product": "Gaming PC",
  "amount": 2500.00,
  "status": "Shipped"
}

###

### Delete an Order (Requires Admin Role)
DELETE {{OrderManagementSystem_HostAddress}}/api/Orders/1  {{-- Replace 1 with an actual Order ID --}}
Accept: application/json
Authorization: Bearer gjiDIGNymraFK5oqcU96ZMFABYOv8DeAJC1XVkXPN8U=

###
